refactored code

diff --git a/.github/workflows/cd-docker-render.yml b/.github/workflows/cd-docker-render.yml
--- a/.github/workflows/cd-docker-render.yml
+++ b/.github/workflows/cd-docker-render.yml
@@ -49,12 +49,12 @@ jobs:
           docker tag $REPOSITORY:$VERSION $PACKAGE_PATH:latest
       - name: Push Docker image to GitHub Container Registry
         run: |
-           docker push $PACKAGE_PATH:$VERSION
-           docker push $PACKAGE_PATH:latest
+          docker push $PACKAGE_PATH:$VERSION
+          docker push $PACKAGE_PATH:latest
       - name: Deploy on Render
         # En Render, en el servicio Web, Settings >> Deploy Hook >>  copiar el token de acceso
         # En GitHub, en el repositorio, Settings >> Secrets and variables >> Actions >> definir la variable de entorno
         # DEPLOY_HOOK_TOKEN con el token
         run: |
-           curl --fail -X POST "https://api.render.com/deploy/${{ secrets.DEPLOY_HOOK_TOKEN }}" || { echo "Deployment failed"; exit 1; }
-           echo "Deployment succeeded"
+          curl --fail -X POST "https://api.render.com/deploy/${{ secrets.DEPLOY_HOOK_TOKEN }}" || { echo "Deployment failed"; exit 1; }
+          echo "Deployment succeeded"
